INSERT IGNORE INTO client_details (id, client_id, client_secret, client_name, dynamically_registered, refresh_token_validity_seconds, access_token_validity_seconds, id_token_validity_seconds, allow_introspection, token_endpoint_auth_method, subject_type, logo_uri) VALUES
  (1, 'client', 'secret', 'Test Client', false, null, 3600, 600, true, null, null, null),
  (7, 'fhir_demo', NULL, 'FHIR Demo App', false, null, 3600, 600, true, "NONE", "PUBLIC", "https://content.hspconsortium.org/images/hspc/icon/HSPCSandboxNoIconApp-210x150.png");

INSERT IGNORE INTO client_scope (owner_id, scope) VALUES
  (1, 'openid'),
  (1, 'profile'),
  (1, 'smart/orchestrate_launch'),
  (1, 'launch'),
  (1, 'launch/patient'),
  (1, 'launch/encounter'),
  (1, 'launch/resource'),
  (1, 'launch/other'),
  (1, 'user/Patient.read'),
  (1, 'user/*.*'),
  (1, 'user/*.read'),
  (1, 'patient/*.*'),
  (1, 'patient/*.read'),
  (1, 'offline_access'),
  (2, 'openid'),
  (2, 'profile'),
  (2, 'smart/orchestrate_launch'),
  (2, 'launch'),
  (2, 'launch/patient'),
  (2, 'launch/encounter'),
  (2, 'launch/resource'),
  (2, 'launch/other'),
  (2, 'user/Patient.read'),
  (2, 'user/*.*'),
  (2, 'user/*.read'),
  (2, 'patient/*.*'),
  (2, 'patient/*.read'),
  (2, 'offline_access'),
  (3, 'openid'),
  (3, 'profile'),
  (3, 'smart/orchestrate_launch'),
  (3, 'launch'),
  (3, 'launch/patient'),
  (3, 'launch/encounter'),
  (3, 'launch/resource'),
  (3, 'launch/other'),
  (3, 'user/Patient.read'),
  (3, 'user/*.*'),
  (3, 'user/*.read'),
  (3, 'patient/*.*'),
  (3, 'patient/*.read'),
  (3, 'offline_access'),
  (7, 'openid'),
  (7, 'profile'),
  (7, 'smart/orchestrate_launch'),
  (7, 'launch'),
  (7, 'launch/patient'),
  (7, 'launch/encounter'),
  (7, 'launch/resource'),
  (7, 'launch/other'),
  (7, 'user/Patient.read'),
  (7, 'user/*.*'),
  (7, 'user/*.read'),
  (7, 'patient/*.*'),
  (7, 'patient/*.read'),
  (7, 'offline_access');

INSERT INTO client_redirect_uri (owner_id, redirect_uri) VALUES
  (1, 'http://localhost/'),
  (1, 'http://localhost:8060/'),
  (2, ''),
  (3, 'http://localhost:8000/fhir-app/'),
  (7, '');

INSERT IGNORE INTO client_grant_type (owner_id, grant_type) VALUES
  (1, 'authorization_code'),
  (1, 'urn:ietf:params:oauth:grant_type:redelegate'),
  (1, 'implicit'),
  (1, 'refresh_token'),
  (2, 'implicit'),
  (2, 'refresh_token'),
  (2, 'authorization_code'),
  (3, 'implicit'),
  (3, 'refresh_token'),
  (3, 'authorization_code'),
  (7, 'implicit'),
  (7, 'refresh_token'),
  (7, 'authorization_code');
